### PR TITLE
Styling photo page

### PR DESCRIPTION
**Pull request by Jen-Harris**
#78 #79 #80 
Updates copy, adds functional upload button and can turn on camera

Still requires: 
* Examples of good/bad images 
* buttons to appear to take photo after selected "take photo"

### CODE REVIEW

**Comment by Jen-Harris** [comment]
Now has good and bad examples 
image

**Comment by Jen-Harris** [comment]
image
 progress

**Review by maxgerber — APPROVED** [review]

**Comment by maxgerber** [comment]
Is this ready to be merged @Jen-Harris  ?

**Comment by Jen-Harris** [comment]
image

**Comment by Jen-Harris** [comment]
ready now @maxgerber !

**Pull request merged**
